# Generated by Django 3.1.14 on 2024-02-27 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='название')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='японское название')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='английское название')),
                ('photo', models.ImageField(default=None, null=True, upload_to='Downloads')),
                ('description', models.TextField(blank=True, max_length=1000, verbose_name='описание')),
                ('level', models.IntegerField(blank=True, verbose_name='уровень')),
                ('health', models.IntegerField(blank=True, verbose_name='здоровье')),
                ('attack', models.IntegerField(blank=True, verbose_name='атака')),
                ('defense', models.IntegerField(blank=True, verbose_name='защита')),
                ('stamina', models.IntegerField(blank=True, verbose_name='выносливость')),
                ('previous_evolution', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(max_length=200, verbose_name='lat')),
                ('lon', models.FloatField(max_length=200, verbose_name='lon')),
                ('appeared_at', models.DateTimeField(verbose_name='appeared_at')),
                ('disappeared_at', models.DateTimeField(verbose_name='disappeared_at')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon')),
            ],
        ),
    ]
